ceph/cbt

benchmark/radosbench.py
Add missing application name in `mkpool()`.
=> benchmark/radosbench.py: add pool application

benchmark/benchmark.py, benchmark/librbdfio.py, benchmark/radosbench.py, settings.py
This PR is aimed at eliminating the directory hierarchy approach of cbt to archive results.
Currently, we have an implementation for the following benchmarks:
- radosbench
- librbdfio
We also store the parameters of the cbt run in yaml format inside the archive directory.
=> benchmark: remove directory hierarchy structure of CBT results

monitoring.py
This change seems to be particularly required for Ubuntu. On Fedora and CentOS, collectl works with or without the escape character in the regex.
Here's what we want to avoid in Ubuntu:
`Quantifier follows nothing in regex; marked by <-- HERE in m/+ <-- HERE cciss/c\d+d\d+ |hd[ab] | sd[a-z]+ |dm-\d+ |xvd[a-z] |fio[a-z]+ | vd[a-z]+ |emcpower[a-z]+ |psv\d+ |nvme[0-9]n[0-9]+p[0-9]+ / at /usr/share/collectl/formatit.ph line 235.`
=> monitoring.py: add escape character to regex

monitoring.py
On ubuntu, collectl V3.6.9-1 (zlib:2.06,HiRes:1.9725) required an escape character in the beginning of the regex. However, collectl V4.0.4-1 (zlib:2.068,HiRes:1.9726) does not require this.
=> monitoring.py: revert to old regex

monitoring.py
=> monitoring.py: use killall instead of pkill

benchmarkfactory.py
@markhpc I think this can resolve the issue seen in https://tracker.ceph.com/issues/40120. Let me know if this is what you were thinking.
=> benchmarkfactory.py: remove CephFSFio dependency

benchmark/fio.py, benchmark/librbdfio.py, benchmark/radosbench.py, client_endpoints/ceph_client_endpoints.py, cluster/ceph.py, settings.py
This PR allows string and list representation of mons in the yaml to work when building a cluster and using client endpoints.
String representation: 
```yaml
mons: "localhost"
```
or
```yaml
mons: "127.0.0.1"
```
List representation:
```yaml
mons: ["localhost"]
```
or
```yaml
mons:["127.0.0.1"]
```
Dict representation:
```yaml
mons:
localhost:
a: "127.0.0.1:6789"
```
usernames for ssh/pdsh can also now be specified on a per-host basis that override the global user setting:
```yaml
mons: "user@localhost"
```
```yaml
mons: ["user@localhost"]
```
```yaml
mons:
user@localhost:
a: "127.0.0.1:6789"
```
Currently the string and list representation will assume that mon ids are listed starting with "a" and ending with "z".  dns resolution is used to find the ip to use when creating the monitor …
=> cluster/ceph: Allow string/list representation for mons/osds/clients

benchmark/fio.py
=> benchmark/fio: fix naming to including ep_num

benchmark/radosbench.py
there is chance that neither "prefill_objects" with "prefill" mode set
nor
"max_objects" is set. in that case, we should not panic.
also the "max-objects" option was introduced by
3ce648d349e1e51b6324a237a665fbd0f54b8996 in ceph/ceph, so the first
release of `rados` cli utilities had this feature was jewel, which is
v10.0:
$ git tag --contains 3ce648d349e | head
v10.0.4
v10.0.5
v10.1.0
v10.1.1
v10.1.2
v10.2.0
v10.2.1
v10.2.10
v10.2.11
v10.2.2
=> benchmark/radosbench: do not error out if max_objects is not set

tools/ceph_rocksdb_log_parser.py
We apparently changed the timestamp format in the OSD logs, so try parsing both ways.
=> tools/ceph_rocksdb_log_parser.py: update timestamp parsing.

benchmark/radosbench.py, common.py, monitoring.py
as on some distro, `perf` actuall execv another `perf_*` to do its job,
so we cannot use `pkill` to kill `perf`
=> monitoring: kill local "perf" processes by their pids

tools/fio_objectstore_tools/analyze.py, tools/fio_objectstore_tools/bluestore_throttle_tuning.rst, tools/fio_objectstore_tools/graph.py, tools/fio_objectstore_tools/hdd-runs.json, tools/fio_objectstore_tools/nvme-runs.json, tools/fio_objectstore_tools/run.py, tools/fio_objectstore_tools/summarize.py, tools/fio_objectstore_tools/traces.py
This adds a few python scripts for initializing, running, and
analyzing benchmark runs using the fio_ceph_objectstore backend.
The tooling is focused on understanding the
latency/throttle/throughput relationship for a particular
device.
Signed-off-by: Samuel Just <sjust@redhat.com>
=> fio_objectstore_tools: utilities for tracing fio_ceph_objectstore

common.py
in python3, they are bytes. so before concatenating them, we need to
decode them into str
=> common: decode the outputs from Popen.communicate()

common.py
In testing on o10, certain commands being passed to join_nostr were of type "unicode" rather than "str".  The existing join_nostr code would put spaces between every character in the unicode string and return it leading to unfortunate errors.  Instead, only execute the join if command is explicitly a list and break up the single line statement so we can easily add other conditions if desired down the road.
=> common: fix join_no_str to join on list vs join on not str

benchmark/librbdfio.py, cluster/ceph.py
Don't convert options like time, ramp and end_fsync to string before
checks as it's possible that they could be set to None value causing fio
script to fail.
Set 'vol_object_size' to 22 instead of '4M' since the option '--order'
is passed to 'rbd create' command. The '--order' is deprecated but will
still work. This option is retained so that testing on older ceph releases
remains unbroken.
Wrap the execution 'rbd create' command within try..catch block to catch
and report actual error for quicker debugging. Also, pass a False value
for 'continue_if_error' in pdsh(..) so that the exception can be caught.
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>
=> librbdfio: Fix a few incorrect options passed to 'fio' & 'rbd create' command.

tools/fio_visualize_data/fio-plot-stats-usage.rst, tools/fio_visualize_data/fio-plot-stats.py, tools/fio_visualize_data/fioplotter.py, tools/fio_visualize_data/fiostatsparser.py
Tool to parse Fio workload generation results for interesting statistics
and generate PyPlot graphs. The idea is for the script to parse both
json and csv output and create meaningful plots to provide insights into
ceph performance.
The code most certainly needs rework to make it generic. One of the
thoughts is to provide the plot specific metadata in a yaml file so that
a lot of the plot specific items (labeling, legends etc.) in the script are
read from it rather than setting them within the script.
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>
=> tools: Add scripts to visualize fio output

cluster/ceph.py
Ceph now requires a flag (and a ceph.conf option!) when pool size is set to one.
=> cluster/ceph: Add the now mandatory pool size 1 flag

tools/fio_visualize_data/fioplotcommon.py, tools/fio_visualize_data/fioplotter.py, tools/fio_visualize_data/fiostatsparser.py
Implement a simpler mechanism using regular expression module to sort
keys of plot data. Filenames containing fio data form the keys of a plot
data dictionary. The keys may be text, numeric or alphanumeric. Use the
inbuilt python function 'sorted()' and provide a custom key function that
sorts the keys in natural order. Factor out this sorting function to a
common library.
=> tools/fio_visualize_data: Sort fio results based on output filenames

cluster/ceph.py
there is chance that we run cbt against a vstart cluster which puts the
asok files in $TMPDIR instead of /var/run/ceph. so. in this chance,
use `ceph daemon` instead of `ceph --admin-daemon <path>` to let `ceph`
cli to deduce the path of asock by itself to avoid hardwire the path to
/var/run.
=> cluster/ceph: do not specify asok path explicitly

benchmark/benchmark.py, monitoring.py
@tchaikov brought to my attention a failure when running CBT and trying to extract CPU metrics using perf without the correct privilege levels: https://github.com/ceph/ceph/pull/35750#issuecomment-650573878
This PR fixes it by:
1. Splitting the regex responsible for extracting CPU cycles so that we can handle NoneType.
2. Adding a warning for the user in case perf failed to collect CPU stats due to permission issues.
=> Fix perf failure to collect stats from CPU due to permission issues

cluster/ceph.py
Currently sshtarget was only being used to create the pdshhost line when starting osds, but not the mgr/mds/rgw daemons.  This PR fixes that so these daemons start properly when user isn't defined.
=> cluster/ceph: use sshtarget to find pdshhost string for mgr/mds/rgw

tools/crimson/README.rst, tools/crimson/seastore_radosbench_analyze.py, tools/crimson/seastore_radosbench_run.sh
Reuse the previous metric file as the starting point, so we don't need
to collect result_metrics_start.log for each rados bench round.
=> tools/crimson: collect and parse metrics incrementally

tools/crimson/seastore_metrics_analyze.py
On-the-fly transactions can cause temporary inconsistent metrics, so
tolerate that in parser.
=> crimson/tools: tolerate temporary inconsistancy of created transactions

tools/crimson/README.rst, tools/crimson/rados_bench_tools.py
Rewrite the structure of the code for future extending.
Support multiple clients and mutliple threads test in the same time.
Support stopping collecting the reactor utilization for the bluestore
comparison testing.
Make it easier to use.
Signed-off-by: Xinyu Huang <xinyu.huang@intel.com>
=> crimson/tools: rados bench stress tool

tools/crimson/README.rst, tools/crimson/rados_bench_tools.py
Support perf analyse.
Support rand read base case.
Support different types of base case threads running parallel and
users can set the running clients ratio of different types of cases
such as 75% of read and 25% of write.
Add pre process and post process interface methods.
Signed-off-by: Xinyu Huang <xinyu.huang@intel.com>
=> crimson/tools: stress tool update

benchmark/hsbench.py
Add an option to hsbench to add unique per-client object prefixes based on the fqdn and endpoint id for each hsbench process.  This ensures that the same data isn't being written to or read when multiple clients are working in a single bucket.
=> benchmark/hsbench: Add a per-client object prefix option

benchmark/fio.py, benchmark/getput.py, benchmark/hsbench.py, benchmark/radosbench.py
Start using pathlib to generalize benchmark cleanup since the supplied command name may not match the current hardcoded executable names we currently use.
=> benchmark: Use pathlib to generalize benchmark cleanup.

benchmark/fio.py
Add fio's sync option to the benchmark wrapper (Used for example to test small sequential sync writes).
=> benchmark/fio: Add sync option

benchmark/benchmark.py, benchmark/fio.py, benchmark/hsbench.py, cbt.py
Currently only the fio based benchmarks in CBT support the concept of prefill.  When a benchmark is run, they will optionally prefill the volume before running benchmarks.  The problem is that this is local and only happens when the first invocation of an fio benchmark is run.
IE if you are running an hsbench benchmark and then an fio benchmark you would:
1) run first hsbench benchmarks (no prefill for hsbench now)
2) prefill rbd
3) run first rbd benchmarks
4) run second hsbenchmarks (no prefill, so recreate data)
5) run second rbd bencharks (using the prefilled data from the first run)
This PR makes the concept of prefill generic for all benchmarks and prefills all benchmark data (when possible/desired) before tests are run.  Now you can do things like:
1) prefill hsbench
2) prefill fio …
=> benchmark: Generalize prefill and add hsbench support

cbt.py, cluster/ceph.py
Fix for use_existing after #249 merged.  Also remove unused osd_count from ceph cluster class that required unnecessary fields in the yaml when use_existing is invoked.
=> cbt: use_existing fixes for #249

common.py, settings.py
The goal here is two-fold:
1) Allow direct path to pdsh commands
2) Allow pdsh environment variables to be set for things like credential pass-through (ie this will enable cbt to run on Red Hat's gibba cluster).  For example, the following can now be added to cbt yaml files:
```
common:
pdsh_ssh_args: "-A"
pdsh_cmd: "/usr/local/bin/pdsh"
pdcp_cmd: "/usr/local/bin/pdcp"
rpdcp_cmd: "/usr/local/bin/rpdcp"
```
=> common: Allow pdsh command pass-through

tools/crimson/seastore_metrics_analyze.py
Due to https://github.com/ceph/ceph/pull/46885
=> tools/crimson/seastore_metrics_analyze: rename segment_cleaner to async_cleaner

cbt.py
after commit 43b553579f6c36b63027b31c7dbb6d0de7e46bed merge that handle prefill we are checking if folder exist after initialize and it will cause the run to skip the test.
i Added also check to do the test in case it is teuthology run, we will skip all the test since we are using exist cluster.
=> cbt: fix prefill skips

tools/crimson/README.rst
fix readme examples due to change of https://github.com/ceph/cbt/pull/287 (--taskset -> --bench-taskset)
=> crimson/tools: update readme

tools/crimson/bench_config.yaml, tools/crimson/crimson_auto_bench.py, tools/crimson/crimson_bench_tool.py
Write yaml file and run ./crimson_auto_bench.py to run multiple tests according to the yaml file and analyse results and draw graphics. 
Use --run to run the whole process, --bench to only run tests, --ana to organize data and draw graphics for exist bench results.
Use --repeat to decide the repeat times for every test.
All repeat results will be drawed as a point in the result graphics, and the mean value will be drawed as a mean line.   
By default, each tests configed in the yaml file are draw in dependent graphics, if you want to compare multiple tests in the config file, use --comp, and all tests will be drawed in one graphics. But be careful, when using --comp, you must write the same --x target config in config file.
You can set --x and multiple --y to decide what index the target …
=> tools/crimson: introduce crimson auto bench tool

tools/crimson/crimson_bench_tool.py
remove all sudos
move reset_task_done() to a more appropriate position
fix pre write will not reset_task_done()
fix timepoint case will not check tester failed when waitting
fix fio(abnormal exit) not been killed in general preprocess
avoid non client task to set_task_done()
=> tools/crimson: misc improvements and fixes on task control

tools/crimson/README.rst, tools/crimson/bench_config.yaml, tools/crimson/crimson_auto_bench.py, tools/crimson/crimson_bench_tool.py, tools/crimson/fio_config.yaml
1. fix path problem
2. integrate rados pre write into retry mechanism
3. optimize graphics and result analysis
4. record key cmd to cmd_log.txt
5. record crimson_bench_tool crash caused by config/unkown error
6. print retry information
7. add repeat num to graphic
8. do device basic tests before ceph tests
9. update isolate alien cores setting
10. use osd_op_num_shards = smp by default.
11. graphic: let y axis start from zero by default
12. graphic: add option --no-start-from-zero
13. config: use MGR=0
14. config: adjust --client param
15. config: adjust --run, --bench param
16. config: add --simple-result
17. config: use block_size = 4K if no input
18. add gap between each test in crimson auto bench
19. add simple alias for all param
20. adjust process killing to avoid zombie process
21. …
=> tools/crimson: functions updates and fixes on tool

tools/fio-parse-jsons/README.md, tools/fio-parse-jsons/fio-parse-jsons.py
This is the separate commit only for the new standalone tool as described in https://github.com/ceph/cbt/pull/306.
This script processes a list of FIO JSON output files and produces as output:
- a gnuplot script, 
-  a .dat file with the data to plot,
-  a summary table of FIO results in wiki format, printed to stdout.
This is especially useful to produce a response graph from a set of executions ranging the number of FIO jobs and the iodepth values. The script was written before knowledge of CBT was gained, so in a way is independent of the script driving the tests. A future PR would integrate the functionality of this standalone script with that of CBT.
The following is an example of the execution of the script:
```bash
```
the arguments are:
-  `-c config_file`: a txt file containing …
=> Add fio-parse-jsons.py tool to parse a set of json FIO files.

benchmark/benchmark.py, benchmark/librbdfio.py, cbt.py, common.py, example/rbd_fio_test.yml, monitoring.py, settings.py
This is my first PR, please be gentle in the review. We add the following new features into the CBT for the benchmark librbdfio:
-  Extend the test plan .yml with a new block section 'workloads' to allow a list of performance tests to be indicated, each with its own range of iodepth and numjobs to iterate. An example of this is provided in `example/rbd_fio_test.yml`
- Extend librbdfio.py with support for such 'workloads' block.
The value of this new workloads block is to allow a finer description of a test job, for example, indicating a range for the iodepth and numjobs FIO parameters, as well as whether to monitor the execution (eg. with perf, top, or collectl). This allow the collection of measurements for computing a response curve.
Here is a snippet that describes:
- a precondition …
=> Extend librbdfio.py with a new workloads block. Add minor fixes.

common_output_formatter.py, tests/test_common_output_formatter.py, tools/fio_common_output_wrapper.py
This PR is the foundation for the work to get CBT to automatically produce a hockey-stick output curve of IOps or Bandwidth vs Latency.
It consists of a python class that will convert the json output from an fio benchmark run in CBT to a common intermediate format, the unit tests for that class, and a wrapper around the class allowing it to be run independently.
The vision is that eventually there will be a class or classes to convert the results from any CBT benchmark run into this intermediate format. This will then allow a single class/utility to be written to produce hockey-stick curves from any CBT benchmark run results.
The next steps are to write the class to plot the data, and then add the code to CBT so it gets run as part of a fio benchmark, possibly using an option in the CBT …
=> Create a intermediate file format from a set of fio results

plot_results.py, plotter/common_format_plotter.py, plotter/directory_comparison_plotter.py, plotter/file_comparison_plotter.py, plotter/simple_plotter.py, requirements.txt, tools/plot_comparison.py
This PR is the second piece of work to get to the point where we can automatically produce plots from a CBT run.
At the moment it will only work with fio test runs, but the plan is to extend it in future to work with any set of CBT results
It follows on from [PR 319](https://github.com/ceph/cbt/pull/319) and uses the common format file as a basis for each plot.
The code is structured in such a way that it can be called from existing CBT code, or run as a stand-alone python script, which is included in this PR.
The code uses the [matplotlib.pyplot](https://matplotlib.org/) library to generate the graphs, so this has been added to the requirements.txt file
The included python script can be used to plot multiple curves on a single image.
This can be 2 or more specified json files in the PR …
=> Add tools and code to produce hockey stick curves for a test run from a PR 319 format json results file

tools/diskstat_diff.py, tools/fio-parse-jsons/fio-parse-jsons.py, tools/gen_json_xtractor.py, tools/gnuplot_plate.py, tools/parse-top.py, tools/report_gen.py, tools/test_run_spec.py
This PR introduces some new tools:
- `report_gen.py` - script that traverses the dir tree to select .JSON entries to produce a report in .tex (uses some existing templates with contents to add, like the header, table of contents, etc.)
- `diskstat_diff.py` - script to filter disk utilisation, producing a .JSON as result, ready to plot, etc.
- `top-parser.py` - script to filter .JSON files from top (translated by jc), calculating averages for CPU and MEM utilisation, used to combine this data with .JSON from FIO.
- `gnuplot_plate.py` - thin wrapper around gnuplot to generate Response latency curves (hockey stick performance charts). 
- `gen_json_xtractor.py, test_run_spec.py` - refactoring of fio-parse-jsons.py into modules that can be reused by other tools.
All the scripts have a --help …
=> First version of the report generator. Add further tools.

post_processing/README.md, post_processing/formatter/README.md, post_processing/plotter/README.md, post_processing/reports/README.md
This PR adds documentation in the form of README.md files for the post processing tools added in PRs [319,](https://github.com/ceph/cbt/pull/319), [321](https://github.com/ceph/cbt/pull/321), [322](https://github.com/ceph/cbt/pull/322) and [323](https://github.com/ceph/cbt/pull/323).
A top-level readme has been created that then links to the readmes for each of the individual parts that make up this work.
=> Documentation for the post processing tools

post_processing/formatter/test_run_result.py
With the inclusion of the total_iodepth feature in [PR324](https://github.com/ceph/cbt/pull/324) the post_processing modules now give eratic results. 
This is because currently the code uses the iodepth value from the fio logs, and not the total_iodepth value set as that is never passed to fio.
The temporary fix is to parse the total_iodepth number from the file path used for the fio results run via CBT (taken from the write_iops_log value stored in the fio output file.
A better fix can be done when the workloads code is split into its own module, and we can write the total_iodepth value somewhere that the post_processing code can read, or we have a better way to cnnect the fio results to the workload that ran it. Until then, this code will allow the post processing to work with the …
=> Fixes for post_processing code for the total_iodepth feature

benchmark/librbdfio.py
This PR adds the "pre_workload_script" to a workload specified in the configuration yaml file. It is specific to the workload, and has no effect outside of the workloads section of the yaml file.
For more information see the [workloads](https://github.com/ceph/cbt/blob/master/docs/Workloads.md) documentation in CBT.
It is the user responsibility to make sure that the script is available at the same path for all clients used in the test run. 
The script must exit with a return code that matches the OS schema i.e. for Linux return code 0 is good, and anything else is considered bad.
The script is run on every client using the standard common.pdsh() method in CBT.
This has been tested locally with a script that deletes and recreates volumes for a workload to run on before the fio IO is run. …
=> Adding an option for a pre-workload script that is run before the IO exerciser

benchmark/librbdfio.py, tools/serialise_benchmark.py
This is a continuation of PR 324
Add an option to the CBT configuration yaml file called total_iodepth. The total_iodepth is then split evenly among the number of volumes used for the test. If the total_iodepth for a run does not divide evenly into the number of volumes, then any remainder will be assigned 1iodepth at a time to the volumes, starting at 0.
For (a simple) example: 
For an total_iodepth of 18 and volumes_per_client of 5, the following iodepth allocations would occur:
| volume | iodepth |
| :---: | :---:|
| 0 | 4 |
| 1 | 4 |
| 2 | 4 |
| 3 | 3 |
| 4 | 3 |
If the number of volumes specified is such that there is not enough iodepth for 1 per volume, then the number of volumes for that test will be reduced so that an iodepth of 1 per volume can be achieved.
Example:
For …
=> Adding a total_iodepth option for librbdfio

benchmark/librbdfio.py
Closes #331 
Change the typing used in librbdfio to use the old style so it is compatible with python versions <3.9 to run in theutology against Ceph versions <Reef
**Testing:**
============================= slowest 5 durations ==============================
0.01s setup    tests/test_bm_hsbench.py::TestBenchmarkhsbench::test_valid_archive_dir
0.01s setup    tests/test_bm_radosbench.py::TestBenchmarkradosbench::test_valid_archive_dir
0.01s setup    tests/test_bm_rawfio.py::TestBenchmarkrawfio::test_valid_archive_dir
0.01s setup    tests/test_bm_getput.py::TestBenchmarkgetput::test_valid_archive_dir
0.01s setup    tests/test_bm_cephtestrados.py::TestBenchmarkcephtestrados::test_valid_archive_dir
======================== 326 passed, 3 skipped in 0.42s ========================
Finished …
=> Changes to support typing on python < 3.9 

post_processing/common.py, post_processing/plotter/common_format_plotter.py, post_processing/plotter/directory_comparison_plotter.py, post_processing/plotter/file_comparison_plotter.py, post_processing/plotter/simple_plotter.py, post_processing/reports/report_generator.py, post_processing/reports/simple_report_generator.py, tools/generate_comparison_performance_report.py, tools/generate_performance_report.py
A few quality of life improvements to the report generation added in #320 #321 and #322.
1. Move the plot legends outside of the graph axes so that it doesn't cover the data. 
The automatic placement was good in most cases, but there were odd cases where data was obscured
2. Some plot titles were given to 1 decimal place - change this back to 0 decimal places
e.g. **1024K** instead of **1024.0K**
3. An option to not draw error bars on the plots in a report.
It was found that some error bars were so big that they ended up distorting the axes and stretching the plot
4. An option to force the regeneration of the intermediate data and plots from the raw data
In 3, and 4 above the current behaviour will remain the default. For 1 and 2 this will become the new default as it makes the charts …
=> Improvements to the report generation
