README.md

Minor fix to readme so it get displayed nicely on github

Markdownizing README

---

benchmark/cephtestrados.py
benchmark/librbdfio.py
benchmark/radosbench.py
benchmark/rbdfio.py
cluster/ceph.py

cluster/ceph.py: provide per-pool application information.

---

benchmark/librbdfio.py
benchmark/radosbench.py

This PR extracts the outputs of radosbench and librbdfio benchmarks and stores them in json format in CBT's archive directory.

benchmark: parse output and store in json format

---

benchmark/librbdfio.py
benchmark/rbdfio.py
cluster/ceph.py

- updated librbdfio.py
- updated rbdfio.py
- updated ceph.py
New parameter '--object-size' will be used instead of deprecated parameter '--order' for RBD image creation
Signed-off-by: Sidhant Agrawal <sagrawal@redhat.com>

Updated parameter in RBD create command

---

cluster/ceph.py

This PR fixes issues when creating a cluster with cephx authentication.

cluster/ceph: fix auth support.

---

benchmark/librbdfio.py
example/bluestore/runtests.bluestore_example.yaml

Signed-off-by: Mohamad Gebai <mgebai@suse.com>

Allow enabling and disabling granular fio logs

---

benchmark/librbdfio.py
example/bluestore/runtests.bluestore_example.yaml

Signed-off-by: Mohamad Gebai <mgebai@suse.com>

Allow setting the pool and rbd names for librbdfio

---

benchmark/benchmark.py
benchmark/kvmrbdfio.py
benchmark/librbdfio.py
benchmark/rawfio.py
benchmark/rbdfio.py
example/wip-mark-testing/runtests.xfs.yaml

Signed-off-by: Mohamad Gebai <mgebai@suse.com>

Allow disabling granular fio logs for all backends

---

benchmark/benchmark.py
benchmark/fio.py
benchmarkfactory.py
cbt.py
client_endpoints/ceph_client_endpoints.py
client_endpoints/cephfsfuse_client_endpoints.py
client_endpoints/cephfskernel_client_endpoints.py
client_endpoints/client_endpoints.py
client_endpoints/librbd_client_endpoints.py
client_endpoints/rbdfuse_client_endpoints.py
client_endpoints/rbdkernel_client_endpoints.py
client_endpoints/rbdnbd_client_endpoints.py
client_endpoints/rbdtcmu_client_endpoints.py
client_endpoints_factory.py
cluster/ceph.py
cluster/cluster.py
settings.py

client_endpoints: Create new client endpoints and demo fio benchmark.

---

tools/config_class.py

Signed-off-by: Nobuto Murata <nobuto.murata@canonical.com>

Fix syntax error of generated YAML

---

settings.py

settings: Don't shutdown when there are no client_endpoints.

---

cluster/ceph.py

cluster/ceph.py: bring back mkimage()

---

benchmark/radosbench.py

benchmark/radosbench: Add prefill options.

---

cluster/ceph.py

cluster/ceph: Update recovery test status parsing.

---

client_endpoints/ceph_client_endpoints.py
client_endpoints/cephfsfuse_client_endpoints.py
client_endpoints/cephfskernel_client_endpoints.py
cluster/ceph.py

cluster/ceph: Updates to make auth work properly.

---

example/example-3x-radosbench-crimson.yaml

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

example: bring example config for crimson-osd.

---

cluster/ceph.py

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

cluster/ceph.py: fix typo

---

cluster/ceph.py
common.py

This commit allows to run CBT without these dependencies for a scenario where everything happens on the same, local node..
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

common: don't require pdsh nor ssh for local operations.

---

cluster/ceph.py

cluster/ceph: Fix conf file regression.

---

common.py

https://github.com/ceph/cbt/pull/178/files#diff-cf5a98d3b8ded947cd1a470ce7e3769eR86-R88
introduced a bug where commands executed via sh didn't return the same output as pdsh.  pdsh always prepends the hostname the command was run on with a colon and a space to stdout and stderr while sh does not.  This PR is a bit of a hack that makes it so that local sh execution of commands also prepends the fqdn of the local host to the stderr and stdout output.
Eventually, we probably want to make this cleaner by returning a dict with the stdout, stderr, host, and potentially other information in a more generic way, but for now this gets things working again.

common: fix local sh execution to return same format as pdsh

---

benchmark/radosbench.py

benchmark/radosbench.py: correct read_time and write_time

---

benchmark/cephtestrados.py
benchmark/cosbench.py
benchmark/fio.py
benchmark/getput.py
benchmark/kvmrbdfio.py
benchmark/librbdfio.py
benchmark/nullbench.py
benchmark/rawfio.py
benchmark/rbdfio.py

this addresses the regression introduced by 4c2713ab66

benchmark: add "archive_dir" to all Benchmark constructors

---

benchmark/fio.py
benchmark/hsbench.py
benchmarkfactory.py
client_endpoints/ceph_client_endpoints.py
client_endpoints/client_endpoints.py
client_endpoints/librbd_client_endpoints.py
client_endpoints/rgws3_client_endpoints.py
client_endpoints_factory.py
cluster/ceph.py
example/example-hsbench.yaml

First pass at implementing an S3 client endpoint and wrapper for the hsbench benchmark.  Minimally tested (though appears to be working) so far.

benchmark/hsbench: Initial benchmark and rgw s3 client endpoints

---

benchmark/fio.py

benchmark/fio: fix endpoints_size typo

---

benchmark/fio.py

benchmark/fio: don't convert possible None vals to str before checks

---

common.py

common: Don't invoke local cmd logic when there are multiple nodes

---

common.py

this addresses a regression introduced by 0719b7d8

common: use pdsh if there are multiple nodes

---

benchmark/librbdfio.py
cluster/ceph.py

Add function check_pg_autoscaler() that checks if pg autoscaler is actively running and if so wait for
it to complete. This can be used in cases where the pg autoscaler kicks in before starting the test 
which can skew the test results.
For librbdfio benchmark, add a new option called 'wait_pgautoscaler_timeout' with a default timeout
of -1 (no wait or indefinite timeout) is introduced. This timeout is passed to  check_pg_autoscaler()
that waits for the pg autoscaler activity to  complete. The function is called just prior to starting test 
run in benchmark/librdbfio.py. This may be used for other benchmarks as well going forward.

librbdfio: Wait for PG autoscaler to complete (if active) before starting test.

---

cluster/ceph.py

Log the total number of degraded objects and the current number of
degraded objects during the recovery phase after an osd is brought down
during the recovery test. The purpose of this is to determine various
statistics during recovery operations.

cluster: Log degraded object stats during recovery test.

---

tools/fio_visualize_data/fio-plot-stats.py
tools/fio_visualize_data/fioplotter.py
tools/fio_visualize_data/fiostatsparser.py

For simpler reading and parsing csv data using other tools, sort the
generated csv metrics based on source json fio result files before writing
to output files.
Also, plot data is a dictionary with input filenames representing the key.
Prior to plotting the data, sort the dictionary based on the key so that
the generated plots and legends on the plots are easier to comprehend.

tools/fio_visualize_data: Sort generated results before writing/plotting to output files

---

tools/githubcheck/githubcheck/check.py

githubcheck: fix ctor of Check

---

tools/githubcheck/bin/github-check
tools/githubcheck/githubcheck/check.py

will need it for adding a link to jenkins job

tools/githubcheck: pass details_url and external_id to check

---

cluster/ceph.py

Add disable_balancer option for performance testing.

cluster/ceph: Add option to disable the balancer

---

tools/crimson/README.rst
tools/crimson/seastore_radosbench_analyze.py
tools/crimson/seastore_radosbench_run.sh

run.sh to run rados bench and collect results.
analyze.py to parse the results to diagram.

tools/crimson: add basic utilities to profile seastore using metrics

---

tools/crimson/seastore_radosbench_analyze.py

In order to match diagram trans_invalidate_committed_ratio_by_src.

tools/crimson: elaborate trans_invalidate_committed_ratio_by_extent by source

---

tools/crimson/seastore_radosbench_analyze.py

Parse new metrics introduced by https://github.com/ceph/ceph/pull/42916
Example figures: https://gist.github.com/cyx1231st/9dc8e418c686fa58675f7bc047ba9cb0

tools/crimson: parse tree metrics 

---

tools/crimson/README.rst
tools/crimson/seastore_fio_run.sh
tools/crimson/seastore_metrics_analyze.py

Signed-off-by: chunmei-liu <chunmei.liu@intel.com>

crimson/tools: add fio metrics support

---

tools/crimson/seastore_metrics_analyze.py
tools/crimson/seastore_metrics_run.sh

The metrics PR is at https://github.com/ceph/ceph/pull/43327

crimson/tools: parse new metrics from ool-record and ool-extents

---

tools/crimson/README.rst
tools/crimson/rados_bench_tools.py

Single client and multi client automatically test to understand how to
stress crimson osd.
Integrate IOPS, Bandwidth, Latency and seastar reactor
utilization.
Signed-off-by: Xinyu Huang <xinyu.huang@intel.com>

crimson/tools: rados bench stress tool

---

tools/crimson/seastore_metrics_analyze.py

Parse metrics from https://github.com/ceph/ceph/pull/43617, should not merge before that.

crimson/tools: parse metrics for journal io-depth and batching

---

tools/crimson/seastore_metrics_analyze.py

This is for https://github.com/ceph/ceph/pull/44244

crimson/tools: parse metrics for trans conflict ratio by srcs

---

tools/crimson/seastore_metrics_analyze.py

Parse metrics modified by https://github.com/ceph/ceph/pull/44127

crimson/tools: fix metrics parsing merged journal heads

---

tools/crimson/seastore_metrics_analyze.py

@aisakaki this should be able to report meaningful errors when the metrics don't match.

crimson/tools: misc improvements to seastore_metrics_analyze.py 

---

monitoring.py

Currently perf monitoring in cbt uses the hardcoded pid glob "osd.*.pid" in the pid dir which isn't always universally correct.  Instead allow formatting with custom strings.  Also run perf with sudo given that OSDs may not be deployed as the same user running cbt.

monitoring: fix perf monitoring issues.

---

tools/crimson/README.rst
tools/crimson/crimson_stress_tool.py

modified some formatting and output names
change some experimental parameters
add a thread to detect version
output csv file
change README

tools/crimson: stress tool update

---

tools/crimson/README.rst
tools/crimson/crimson_stress_tool.py

add fio sequence read/write cases.
modified some formatting and output.
code clean up.

tools/crimson/crimson_stress_tool: add fio sequence read/write case 

---

tools/crimson/seastore_metrics_analyze.py

see https://github.com/ceph/ceph/pull/45386

tools/crimson/seastore_metrics_analyze: support record-submitter related metrics

---

tools/crimson/seastore_metrics_analyze.py

Parse metrics from https://github.com/ceph/ceph/pull/46158

tools/crimson/seastore_metrics_analyze: add graph for segment cleaner metrics

---

tools/crimson/seastore_metrics_analyze.py

This PR is dependent on https://github.com/ceph/ceph/pull/46298

tools/crimson/seastore_metrics_analyze: implement graph from seastore added metrics

---

tools/crimson/crimson_stress_visualizer.py

tools/crimson: add crimson multiple stores support

tools/crimson: add crimson multiple stores support

---

tools/crimson/seastore_metrics_analyze.py
tools/crimson/seastore_metrics_run.sh

tools/ crimson:
1. Add fault tolerance for stats data, iostat 11.7.3 issues fixed.
2. Fix metrics file can't be parsed, fix FIO or RADOS test can't be used.
3. Fix issues caused by metrics keys.

tools/crimson: fix bunch of bugs mostly caused by update of upstream Ceph

---

tools/crimson/crimson_bench_tool.py

1. extend smp setting range
2. adjust log output
3. add group gap

tools/crimson: extend smp setting range and adjust log dir

---

tools/crimson/crimson_bench_tool.py

.data file and flamegraph will be stored in task log path

tools/crimson: support perf record and flamegraph for multiple cases

---

tools/crimson/crimson_bench_tool.py

tools/crimson: add commitID and fix latency caculation error

---

tools/crimson/crimson_bench_tool.py

tools/crimson: improve settings for crimson_alien_thread_cpu_cores and crimson_alien_op_num_threads

---

tools/crimson/crimson_bench_tool.py

tools/crimson: improvment about warmup, alienstore, and osd_op_num_shards

---

tools/crimson/crimson_bench_tool.py

Introduce a failure detector thread for every tester to detect task failed such as osd crash, osd write failed, and will automatically rollback test and retry.
@liu-chunmei  @cyx1231st

tools/crimson: introduce failure detect and recovery mechanism

---

tools/crimson/crimson_bench_tool.py

tools/crimson: fio rbd task updates

---

tools/fio-parse-jsons/fio-parse-jsons.py

Minor fix in the format string, and add a multi-column for the OSD CPU util.

Fixed typo in script fio-parse-jsons.py

---

cluster/ceph.py

Add the required flag to make default "." pools now required in Reef.

cluster/ceph: Fix built-in pool creation for Reef.

---

.gitignore
benchmark/benchmark.py
benchmark/librbdfio.py
cli_options.py
command/command.py
command/fio_command.py
command/rbd_fio_command.py
post_processing/common.py
post_processing/formatter/common_output_formatter.py
post_processing/formatter/test_run_result.py
post_processing/log_configuration.py
post_processing/plotter/common_format_plotter.py
post_processing/plotter/directory_comparison_plotter.py
post_processing/plotter/file_comparison_plotter.py
post_processing/reports/comparison_report_generator.py
post_processing/reports/report_generator.py
post_processing/reports/simple_report_generator.py
tools/fio_common_output_wrapper.py
tools/generate_comparison_performance_report.py
tools/generate_performance_report.py
workloads/workload.py
workloads/workloads.py

This PR covers two main themes:
1. Updating librbdfio
- so that it runs the new worload code
- so that it converts the fio output correctly into json format in the results directory
2. Improvement to the post-processing scripts from #319, #320 and #321
- to be able to convert the output from running the new workloads code in #333 
- generate_performance_report.py - so that it generates the intermediate file format for a run before creating the report, if required
- generate_comparison_performance_report.py - so that it generates the intermediate file format for a run before creating the report, if required
- better logging and a separate log file for post processing to aid debugging problems
1. running the new workloads code
2. post processing the results
3. creating a report from the …

Updating post processing

---

workloads/workloads.py

The pre-workload script was only running once per workload, where it should really run once per point for the curve

Fix a problem with the pre-workload script
